import React from 'react';
import AnimatedFadeInContainer from '../components/Layouts/AnimatedFadeInContainer';
import Layout from '../components/Layouts/Layout';

// import Cases from '../sections/Cases/Cases';
// import Hero from '../sections/Hero/Hero';
// import MainPageShortcuts from '../sections/MainPage/MainPageShortcuts';
import Head from 'next/head';

const Frameworks = (): JSX.Element => {
  return (
    <Layout className="bg-slate-100 justify-center align-center flex-col dark:bg-gray-900 min-h-screen relative">
      <Head>
        <title>Martin Lindblad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero />
      <MainPageShortcuts />
      <Cases /> */}
      <Layout className="bg-slate-100 justify-center align-center flex-col dark:bg-gray-900 min-h-screen relative">
        <AnimatedFadeInContainer type="FadeInBottom">
          <h1 className="text-lg font-normal lg:text-xl px-8  text-center lg:w-2/3 mx-auto flex pt-32 lg:pt-10 lg:items-center lg:justify-center w-full lg:container min-h-screen">
            Frameworks
          </h1>
        </AnimatedFadeInContainer>
      </Layout>
    </Layout>
  );
};

export default Frameworks;
