import Head from 'next/head';
import About from 'src/components/About/About';
import Layout from 'src/components/Layouts/Layout';

import Navbar from 'src/sections/navigation/Navbar';

export default function Home() {
  return (
    <Layout className="bg-gray-100 dark:bg-gray-900 min-h-screen">
      <Head>
        <title>Martin Lindblad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <About />
    </Layout>
  );
}
