import Head from 'next/head';
import Layout from 'src/components/Layouts/layout';
import Cases from 'src/sections/Cases/Cases';
import Hero from 'src/sections/Hero/Hero';

import Navbar from 'src/sections/navigation/navbar';

export default function Home() {
  return (
    <Layout className="bg-gray-200 dark:bg-gray-900 min-h-screen relative">
      <Head>
        <title>Martin Lindblad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Cases />
    </Layout>
  );
}
